language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t shrey7197/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shrey7197/docker-react npm run test
      